---
  - name: Download OpenShift with check (sha256)
    get_url:
      url: https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz
      dest: /tmp/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz
      checksum: sha256:6973aebb7b553866f8971c8ca324dd5b79204e2a59c5234cde6fb1b5deb4c7a9

    - name: Untar OpenShift
      unarchive:
        src: /tmp/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz
        dest: /opt

    - name: Create symbolic links
      file:
        src: /opt/openshift-origin-server-v3.10.0-dd10d17-linux-64bit/{{item.name}}
        dest: /usr/local/bin/{{item.name}}
        force: true
        state: link
      vars:
        files:
        - name: hyperkube
        - name: hypershift
        - name: kubectl
        - name: oadm
        - name: oc
        - name: openshift
        - name: openshift-node-config
        - name: template-service-broker
      with_items: "{{ files }}" 

    - name: Create working directory
      file:
        path: /var/lib/openshift
        state: directory
        
    - name: Generate Openshift Service
      template:
        src: openshift.service.j2
        dest: /etc/systemd/system/openshift.service   
        remote_src: true
      
    # - name: Install Openshift Service
    #   copy:
    #     src: /tmp/openshift.service
    #     dest: /etc/systemd/system/openshift.service

    - name: Enable Openshift Service
      systemd:
        daemon_reload: true
        name: openshift.service
        enabled: true
        state: started
        no_block: true
        